name: Run Playwright Test

on:
  workflow_dispatch:

jobs:
  playwright-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}

      - name: Install Chromium only
        run: npx playwright install chromium

      - name: Run Playwright test
        id: playwright-test
        env:
          X_USERNAME: ${{ secrets.X_USERNAME }}
          X_COOKIES: ${{ secrets.X_COOKIES }}
          BLOG_URL: ${{secrets.BLOG_URL}}
          BLOG_USERNAME: ${{secrets.BLOG_USERNAME}}
          BLOG_PASSWORD: ${{secrets.BLOG_PASSWORD}}
          BLOG_NAME: ${{secrets.BLOG_NAME}}
          API_BASE_URL: ${{secrets.API_BASE_URL}}
          API_ID: ${{secrets.API_ID}}
          API_AFFILIATE_ID: ${{secrets.API_AFFILIATE_ID}}
          API_SERVICE: ${{secrets.API_SERVICE}}
          GET_DATE: ${{ vars.GET_DATE }}
          POST_INDEX: ${{ vars.POST_INDEX }}
        run: |
          npx playwright test tests/post.spec.ts

      - name: GITHUB_OUTPUT test
        env:
          NEXT_DATE: ${{ steps.playwright-test.outputs.NEXT_DATE }}
          NEXT_INDEX: ${{steps.playwright-test.outputs.NEXT_INDEX}}
        run: |
          echo "次の記事の日付: $NEXT_DATE"
          echo "次の記事のインデックス: $NEXT_INDEX"
