name: Run Playwright Test

on:
  workflow_dispatch:

jobs:
  playwright-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}

      - name: Install Chromium only
        run: npx playwright install chromium

      - name: Run Playwright test
        id: playwright-test
        env:
          X_USERNAME: ${{ secrets.X_USERNAME }}
          X_COOKIES: ${{ secrets.X_COOKIES }}
          BLOG_USERNAME: ${{secrets.BLOG_USERNAME}}
          BLOG_PASSWORD: ${{secrets.BLOG_PASSWORD}}

        run: |
          npx playwright test tests/post.spec.ts

      - name: GITHUB_OUTPUT test
        env:
          TOTAL_POSTS: ${{ steps.playwright-test.outputs.TOTAL_POSTS }}
        run: |
          echo "TOTAL_POSTS: $TOTAL_POSTS"
